# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
oned_array = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
twod_array = np.array([[1,2,3], [4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
threed_array = np.array([[[1,2,3]], [[4,5,6]], [[7,8,9]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
oned_array.ndim, oned_array.dtype, oned_array.size, type(oned_array)

(1, dtype('int64'), 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
twod_array.ndim, twod_array.dtype, twod_array.size, type(twod_array)

(2, dtype('int64'), 6, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
threed_array.ndim, threed_array.dtype, threed_array.size, type(threed_array)

(3, dtype('int64'), 9, numpy.ndarray)

In [7]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
oned_pandas = pd.DataFrame(oned_array)
oned_pandas

,0
0,1
1,2
2,3


In [9]:
# Create an array of shape (10, 2) with only ones
ones = np.ones(shape=(10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros(shape=(7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
# Create an array within a range of 0 and 100 with step 3
array_steps = np.arange(0, 100, 3)
array_steps

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [14]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
rand1 = np.random.randint(0, 10, size=(7,2))
rand1

array([[6, 2],
       [8, 8],
       [6, 7],
       [5, 9],
       [8, 3],
       [2, 1],
       [3, 9]], dtype=int32)

In [19]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
rand2 = np.random.rand(3,5)
rand2

array([[0.73055603, 0.95423456, 0.62299228, 0.21622848, 0.38512107],
       [0.90683557, 0.66629003, 0.08711425, 0.42419866, 0.34784139],
       [0.0804786 , 0.35972332, 0.0908705 , 0.56293079, 0.85929435]])

In [22]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
rand3 = np.random.randint(0, 10, size=(4,6))
rand3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [24]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
rand4 = np.random.randint(0, 10, size=(3,7))

# Find the unique numbers in the array you just created
np.unique(rand4)

array([0, 1, 2, 3, 4, 5, 6, 7, 9], dtype=int32)

In [25]:
# Find the 0'th index of the latest array you created
rand4[0]

array([4, 1, 3, 6, 7, 2, 0], dtype=int32)

In [26]:
# Get the first 2 rows of latest array you created
rand4[:2]

array([[4, 1, 3, 6, 7, 2, 0],
       [3, 1, 7, 3, 1, 5, 5]], dtype=int32)

In [30]:
# Get the first 2 values of the first 2 rows of the latest array
rand4[:2,:2]

array([[4, 1],
       [3, 1]], dtype=int32)

In [37]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
rand5 = np.random.randint(0, 10, size=(3,5))

rand6 = np.ones((3,5))
rand5

array([[3, 4, 6, 6, 3],
       [6, 2, 5, 1, 9],
       [8, 4, 5, 3, 9]], dtype=int32)

In [38]:
# Add the two arrays together
rand5+rand6

array([[ 4.,  5.,  7.,  7.,  4.],
       [ 7.,  3.,  6.,  2., 10.],
       [ 9.,  5.,  6.,  4., 10.]])

In [39]:
# Create another array of ones of shape (5, 3)
rand7 = np.ones((5,3))

In [40]:
# Try add the array of ones and the other most recent array together
rand6+rand7

# Different shapes unable to broadcast 

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [42]:
# Create another array of ones of shape (3, 5)
rand8 = np.ones((3,5))

In [49]:
# Subtract the new array of ones from the other most recent array
rand8-rand5

array([[-2., -3., -5., -5., -2.],
       [-5., -1., -4.,  0., -8.],
       [-7., -3., -4., -2., -8.]])

In [47]:
# Multiply the ones array with the latest array
rand8 * rand5

array([[3., 4., 6., 6., 3.],
       [6., 2., 5., 1., 9.],
       [8., 4., 5., 3., 9.]])

In [50]:
# Take the latest array to the power of 2 using '**'
rand5 ** 2

array([[ 9, 16, 36, 36,  9],
       [36,  4, 25,  1, 81],
       [64, 16, 25,  9, 81]], dtype=int32)

In [51]:
# Do the same thing with np.square()
np.square(rand5)

array([[ 9, 16, 36, 36,  9],
       [36,  4, 25,  1, 81],
       [64, 16, 25,  9, 81]], dtype=int32)

In [57]:
# Find the mean of the latest array using np.mean()
rand5.mean()

np.float64(4.933333333333334)

In [56]:
# Find the maximum of the latest array using np.max()
rand5.max()

np.int32(9)

In [58]:
# Find the minimum of the latest array using np.min()
rand5.min()

np.int32(1)

In [59]:
# Find the standard deviation of the latest array
rand5.std()

np.float64(2.3513589451397863)

In [60]:
# Find the variance of the latest array
rand5.var()

np.float64(5.528888888888889)

In [61]:
# Reshape the latest array to (3, 5, 1)
rand5.reshape(3,5,1)

array([[[3],
        [4],
        [6],
        [6],
        [3]],

       [[6],
        [2],
        [5],
        [1],
        [9]],

       [[8],
        [4],
        [5],
        [3],
        [9]]], dtype=int32)

In [62]:
# Transpose the latest array
rand5.T

array([[3, 6, 8],
       [4, 2, 4],
       [6, 5, 5],
       [6, 1, 3],
       [3, 9, 9]], dtype=int32)

What does the transpose do?

In [63]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
rand9 = np.random.randint(0, 10, size=(3,3))
rand10 = np.random.randint(0, 10, size=(3,2))

In [64]:
# Perform a dot product on the two newest arrays you created
rand9.dot(rand10)

array([[100, 116],
       [ 64,  32],
       [ 95, 101]], dtype=int32)

In [65]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
rand11 = np.random.randint(0, 10, size=(4,3))
rand12 = np.random.randint(0, 10, size=(4,3))

In [67]:
# Perform a dot product on the two newest arrays you created
rand11.dot(rand12)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [68]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
rand11.dot(rand12.T)

array([[20,  8,  0, 47],
       [61, 20, 49, 47],
       [51, 12, 56, 11],
       [15, 36,  0, 24]], dtype=int32)

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [88]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
rand13 = np.random.randint(0, 10, size=(4,4))
rand14 = np.random.randint(0, 10, size=(4,4))

rand13

array([[6, 0, 2, 1],
       [8, 9, 5, 9],
       [2, 7, 7, 1],
       [5, 6, 1, 9]], dtype=int32)

In [89]:
# Compare the two arrays with '>'
rand13 > rand14

array([[ True, False,  True, False],
       [ True,  True, False,  True],
       [False,  True, False, False],
       [ True, False, False, False]])

What happens when you compare the arrays with `>`?

In [90]:
# Compare the two arrays with '>='
rand13 >= rand14

array([[ True, False,  True, False],
       [ True,  True,  True,  True],
       [False,  True, False, False],
       [ True, False, False,  True]])

In [91]:
# Find which elements of the first array are greater than 7
rand13 > 7

array([[False, False, False, False],
       [ True,  True, False,  True],
       [False, False, False, False],
       [False, False, False,  True]])

In [92]:
# Which parts of each array are equal? (try using '==')
rand13 == rand14

array([[False, False, False, False],
       [False, False,  True, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [93]:
# Sort one of the arrays you just created in ascending order
rand15 = rand13.sort()
rand15

In [95]:
# Sort the indexes of one of the arrays you just created
rand14.argsort()

array([[2, 0, 3, 1],
       [0, 2, 3, 1],
       [3, 1, 0, 2],
       [0, 2, 1, 3]])

In [98]:
# Find the index with the maximum value in one of the arrays you've created
rand14.argmax()

np.int64(1)

In [99]:
# Find the index with the minimum value in one of the arrays you've created
rand14.argmin()

np.int64(2)

In [100]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
rand14.argmax(axis=1)

array([1, 1, 0, 3])

In [101]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
rand14.argmin(axis=0)

array([1, 2, 0, 2])

In [108]:
# Create an array of normally distributed random numbers
rng = np.random.default_rng()
normal_array = rng.normal(loc=0, scale=1, size=1000)
normal_array

array([ 0.53169939, -0.80718693,  1.42196926, -1.00282805, -0.28029464,
        0.15080558,  0.94516747,  0.52653634, -0.19960167, -0.21413967,
        1.02373049,  0.87879267, -0.40640787, -1.1567919 ,  0.116873  ,
        0.83003538,  0.48711324, -0.18814925,  0.04277532, -0.22983605,
        1.83108363, -1.95932876,  1.24733945, -0.06036264, -0.47460425,
        0.21890884, -0.74603912,  0.33783725,  1.34891318, -0.63543004,
       -0.67231035, -0.1405622 , -0.66190107,  1.74213096, -0.33495001,
        0.71843947, -0.16299607, -1.2157478 ,  0.42447569,  2.86841163,
       -0.18496931,  0.75528236, -1.68641286,  0.72416122,  0.17611502,
        0.88302948,  1.59952136, -1.1749918 , -0.39624927,  2.88654659,
        0.78440658, -0.05709495,  0.0504156 ,  0.03387253,  0.38411496,
       -2.1006435 , -0.50798193,  0.17232427, -0.38946203,  0.04397385,
       -0.50963891, -0.31202289,  0.53169248, -0.92535141, -1.69160259,
       -1.12534263,  0.45710805, -1.59803245, -0.40376424, -0.18

In [106]:
# Create an array with 10 evenly spaced numbers between 1 and 100
array = np.linspace(1, 100, 10)
array

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.